# Generated by Django 5.1.5 on 2025-02-07 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_solve_scramble'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solve',
            old_name='date_solved',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='solve',
            name='scramble',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
