# Generated by Django 5.2.1 on 2025-05-13 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solve',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='solve',
            name='time_taken',
            field=models.FloatField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='solve',
            index=models.Index(fields=['-created_at'], name='tracker_sol_created_09dae3_idx'),
        ),
        migrations.AddIndex(
            model_name='solve',
            index=models.Index(fields=['time_taken'], name='tracker_sol_time_ta_bad000_idx'),
        ),
    ]
