# Generated by Django 5.2.3 on 2025-06-27 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_solve_created_at_alter_solve_time_taken_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solve',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='solve',
            name='note',
            field=models.TextField(blank=True, help_text='Optional notes about this solve', max_length=500),
        ),
        migrations.AlterField(
            model_name='solve',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this solve was recorded'),
        ),
        migrations.AlterField(
            model_name='solve',
            name='scramble',
            field=models.CharField(blank=True, help_text='Scramble sequence used for this solve', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='solve',
            name='time_taken',
            field=models.FloatField(db_index=True, help_text='Time taken to solve the cube in seconds'),
        ),
        migrations.AddIndex(
            model_name='solve',
            index=models.Index(fields=['created_at', 'time_taken'], name='tracker_sol_created_b4f735_idx'),
        ),
    ]
