# Generated by Django 5.2.3 on 2025-06-30 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0003_alter_solve_options_solve_note_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CubeType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name="solve",
            name="is_pb",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="solve",
            name="session",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="solve",
            name="tags",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="solve",
            name="cube_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="solves",
                to="tracker.cubetype",
                null=True,
            ),
            preserve_default=False,
        ),
    ]
