# Generated by Django 5.2.3 on 2025-07-01 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_fix_cubetype_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solve',
            name='cube_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solves', to='tracker.cubetype'),
        ),
    ]
