name: CI/CD for RubikLog

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend:
    name: Backend CI
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'preview' }}
    env:
      POSTGRES_DB: rubiklogdb
      POSTGRES_USER: shreyuu
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_HOST: dpg-d0hnhot6ubrc73ah6vig-a.oregon-postgres.render.com
      POSTGRES_PORT: 5432
      DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
      DJANGO_DEBUG: ${{ github.ref != 'refs/heads/main' }}
      DJANGO_ALLOWED_HOSTS: localhost,127.0.0.1,.oregon-postgres.render.com
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug env (without sensitive values)
        run: |
          echo "POSTGRES_USER: $POSTGRES_USER"
          echo "POSTGRES_HOST: $POSTGRES_HOST"
          echo "POSTGRES_PASSWORD is set: ${POSTGRES_PASSWORD:+yes}"
          echo "Current environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'preview' }}"
          echo "Debug mode: ${{ github.ref != 'refs/heads/main' }}"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run migrations
        run: |
          python manage.py migrate

      - name: Run backend tests
        run: |
          python manage.py test --noinput --keepdb

  frontend:
    name: Frontend CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: "frontend/package-lock.json"

      - name: Install dependencies
        working-directory: frontend
        run: |
          npm install
          npm install --legacy-peer-deps
          npm install @testing-library/react@^13.4.0 --save-dev --legacy-peer-deps
          npm install @babel/plugin-proposal-private-property-in-object --save-dev --legacy-peer-deps
          npm install web-vitals@^2.1.4 --save --legacy-peer-deps

      - name: Run frontend tests
        working-directory: frontend
        run: |
          CI=true npm run test

      - name: Build frontend
        working-directory: frontend
        run: |
          npm run build
