name: CI/CD for RubikLog

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend:
    name: Backend CI
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: shreyuu
          POSTGRES_DB: rubiklogdb
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
        ports:
          - 5432:5432
    env:
      DATABASE_URL: postgres://postgres:shreyuu@localhost:5432/rubiklogdb
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Python dependencies
        working-directory: RubikLog
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run migrations
        working-directory: RubikLog
        run: |
          python manage.py migrate

      - name: Run backend tests
        working-directory: RubikLog
        run: |
          python manage.py test

  frontend:
    name: Frontend CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: 'npm'
          cache-dependency-path: './RubikLog/frontend/package-lock.json'

      - name: Install dependencies
        working-directory: RubikLog/frontend
        run: |
          rm -rf node_modules package-lock.json
          npm install
          npm install @testing-library/react@^13.4.0 --save-dev
          npm install @babel/plugin-proposal-private-property-in-object --save-dev

      - name: Run frontend tests
        working-directory: RubikLog/frontend
        run: |
          CI=true npm test -- --watchAll=false

      - name: Build frontend
        working-directory: RubikLog/frontend
        run: |
          npm run build